name: Generate This American Life RSS Feed

on:
  schedule:
    - cron: '0 18 * * 0' # 6 PM every Sunday
  workflow_dispatch: # This line enables manual triggering

jobs:
  scrape-and-generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper script (latest mode)
        run: python tal_scraper.py latest

      - name: Commit and push new feed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add claudeTal.xml
          git commit -m "Auto-generate RSS feed" || echo "No changes to commit"
          git push
