name: TAL Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 0' # Sundays 6 PM UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Scrape TAL
        env:
          SCRAPER_MODE: latest  # "test5", "all", "new_only"
        run: python generate.py

      - name: Commit & push feed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update feed.xml"
          file_pattern: feed.xml
          branch: main
          git_user_name: "GitHub Actions"
          git_user_email: "actions@github.com"
