name: Scrape TAL Archive

on:
  workflow_dispatch:   # manual trigger
  schedule:
    - cron: "0 6 * * 1"   # run every Monday at 06:00 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests beautifulsoup4 lxml

      - name: Run scraper
        run: python generate.py

      - name: Commit & push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add feed.xml
          git diff --quiet && git diff --staged --quiet || git commit -m "Update feed.xml"
          git push
